server:
  host: http://192.168.4.39:8090
  context: /csapp
codis:
  host: 192.168.4.53
  port: 29000
  password: redis
  db: 0
redis:
  host:
    -
     - 192.168.4.21
     - 26379
    -
     - 192.168.4.22
     - 26379
    -
     - 192.168.4.23
     - 26379
mysql:
  host: 192.168.4.13
  port: 3308
  user: sit_nono_app
  password: csstbnonobank@2016
  db: nonobank_app
mongo:
  host: 192.168.3.29
  user: csyy_app
  password: csyyapp@stb
  db: csyy_app_log
